services:
  mysql_db:
    image: 'mysql:9.0'
    environment:
      - 'MYSQL_DATABASE=studentapp_db'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=studentapp_user'
    ports:
      - '3306:3306'